version: '3.1'

services:
  cityvizor-server:
    image: cityvizor
    build: .     
    command: node server/dist/server.js
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on: 
      - postgres

  cityvizor-cron:
    image: cityvizor
    environment:
      NODE_ENV: production
    command: node server/dist/cron.js
    depends_on: 
      - postgres

  # cityvizor-importer:
  #   image: cityvizor
  #   environment:
  #     NODE_ENV: production
  #   command: node dist/importer.js

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
