version: '3.1'

services:
  cityvizor:
    build: .
    container_name: cityvizor
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

postgres:
  image: postgres:11
  environment:
    POSTGRES_PASSWORD: pass
  volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
